services:
  - type: web
    name: twitch-chatgpt-bot
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        value: 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
      - key: CHANNELS
        value: xulaniec
      - key: GPT_MODE
        value: "CHAT"
      - key: HISTORY_LENGTH
        value: "10"
      - key: MODEL_NAME
        value: "gpt-3.5-turbo"
      - key: COMMAND_NAME
        value: "eustahy"
      - key: TWITCH_USER  # https://dev.twitch.tv/console
        value: "xeustahy"
      - key: TWITCH_AUTH  # https://twitchapps.com/tmi/
        value: "oauth:lo8z7au5mivmgug70czr67e81avmad"
      - key: SEND_USERNAME
        value: "true"
      - key: ENABLE_TTS
        value: "false"
      - key: ENABLE_CHANNEL_POINTS
        value: "true"
